version: 2
updates:
  - package-ecosystem: "mix"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "America/New_York"
    labels:
      - "dependencies"
    commit-message:
      prefix: "build"
      include: "scope"
    groups:
      patch-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:30"
      timezone: "America/New_York"
    labels:
      - "dependencies"
    commit-message:
      prefix: "ci"
      include: "scope"
    groups:
      patch-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
    open-pull-requests-limit: 5
