defmodule Rulestead.Test.ReleasePublishFixture do
  @moduledoc false

  @core_consumer_dir "core_consumer"
  @admin_consumer_dir "admin_consumer"
  @admin_contract %{
    mount_path: "/flags",
    session_keys: [
      "current_actor",
      "rulestead_admin_environments",
      "rulestead_admin_last_env"
    ],
    env_query_param: "env"
  }

  def setup_core_consumer!(tmp_dir, version, opts \\ []) do
    version = published_requirement!(version)
    app_dir = Path.join(tmp_dir, @core_consumer_dir)

    run_generator!(
      "mix",
      ["new", @core_consumer_dir, "--sup"],
      tmp_dir,
      opts
    )

    inject_deps!(Path.join(app_dir, "mix.exs"), [{:rulestead, version}])

    %{
      name: :rulestead,
      app_dir: app_dir,
      deps: [%{app: :rulestead, requirement: version}],
      checks: [
        %{cmd: "mix", args: ["deps.get"]},
        %{cmd: "mix", args: ["compile"]}
      ]
    }
  end

  def setup_admin_consumer!(tmp_dir, version, opts \\ []) do
    version = published_requirement!(version)
    app_dir = Path.join(tmp_dir, @admin_consumer_dir)

    run_generator!(
      "mix",
      [
        "phx.new",
        @admin_consumer_dir,
        "--no-assets",
        "--no-dashboard",
        "--no-mailer",
        "--no-ecto",
        "--no-install"
      ],
      tmp_dir,
      opts
    )

    inject_deps!(Path.join(app_dir, "mix.exs"), [
      {:rulestead, version},
      {:rulestead_admin, version}
    ])

    encode_admin_contract!(app_dir)

    %{
      name: :rulestead_admin,
      app_dir: app_dir,
      deps: [
        %{app: :rulestead, requirement: version},
        %{app: :rulestead_admin, requirement: version}
      ],
      checks: [
        %{cmd: "mix", args: ["deps.get"]},
        %{cmd: "mix", args: ["compile"]}
      ],
      contract: @admin_contract
    }
  end

  defp published_requirement!(version) do
    trimmed = String.trim(version)

    cond do
      trimmed == "" ->
        raise ArgumentError, "expected published version"

      String.contains?(trimmed, "path:") ->
        raise ArgumentError, "path dependencies are not allowed"

      String.contains?(trimmed, "/") ->
        raise ArgumentError, "local paths are not allowed"

      true ->
        "~> #{trimmed}"
    end
  end

  defp run_generator!(cmd, args, cd, opts) do
    generator_runner = Keyword.get(opts, :generator_runner, &default_generator_runner/4)
    generator_runner.(cmd, args, cd, opts)
  end

  defp default_generator_runner(cmd, args, cd, _opts) do
    {output, status} = System.cmd(cmd, args, cd: cd, stderr_to_stdout: true)

    if status == 0 do
      output
    else
      raise """
      consumer generator failed: #{cmd} #{Enum.join(args, " ")}
      #{output}
      """
    end
  end

  defp inject_deps!(mix_exs_path, deps) do
    contents = File.read!(mix_exs_path)

    dep_lines =
      Enum.map_join(deps, "\n", fn {app, requirement} ->
        ~s(      {:#{app}, "#{requirement}"},)
      end)

    updated =
      String.replace(
        contents,
        "defp deps do\n    [",
        "defp deps do\n    [\n#{dep_lines}"
      )

    File.write!(mix_exs_path, updated)
  end

  defp encode_admin_contract!(app_dir) do
    router_path = Path.join([app_dir, "lib", "admin_consumer_web", "router.ex"])

    if File.exists?(router_path) do
      updated_router =
        router_path
        |> File.read!()
        |> String.replace(
          "use AdminConsumerWeb, :router",
          "use AdminConsumerWeb, :router\n  use RulesteadAdmin.Router"
        )
        |> append_admin_mount()

      File.write!(router_path, updated_router)
    end

    contract_path = Path.join([app_dir, "config", "rulestead_release_publish_contract.exs"])

    File.mkdir_p!(Path.dirname(contract_path))

    File.write!(
      contract_path,
      """
      # Generated by #{__MODULE__}
      config = %{
        mount_path: "#{@admin_contract.mount_path}",
        session_keys: #{inspect(@admin_contract.session_keys)},
        env_query_param: "#{@admin_contract.env_query_param}"
      }
      """
    )
  end

  defp append_admin_mount(router_source) do
    mount_block = """

      scope \"/\" do
        pipe_through :browser

        rulestead_admin \"#{@admin_contract.mount_path}\", policy: AdminConsumer.RulesteadPolicy
      end
    """

    if String.contains?(router_source, ~s(rulestead_admin "#{@admin_contract.mount_path}")) do
      router_source
    else
      String.trim_trailing(router_source) <> mount_block <> "\n"
    end
  end
end
