[
  # Mix Tasks external deps and no returns
  {"lib/mix/tasks/rulestead.diff.ex", :no_return},
  {"lib/mix/tasks/rulestead.import.ex", :no_return},
  {"lib/mix/tasks/rulestead.promote.ex", :no_return},
  {"lib/mix/tasks/rulestead.validate.ex", :no_return},
  {"lib/mix/tasks/verify.release_parity.ex", :no_return},

  # Credo custom checks using external Credo modules not in PLT
  {"lib/rulestead/credo/no_eval_outside_context.ex", :callback_info_missing},
  {"lib/rulestead/credo/no_eval_outside_context.ex", :unknown_function},
  {"lib/rulestead/credo/no_mutation_outside_multi.ex", :callback_info_missing},
  {"lib/rulestead/credo/no_mutation_outside_multi.ex", :unknown_function},
  {"lib/rulestead/credo/no_raw_traits_in_logger.ex", :callback_info_missing},
  {"lib/rulestead/credo/no_raw_traits_in_logger.ex", :unknown_function},
  {"lib/rulestead/credo/no_raw_traits_in_telemetry_meta.ex", :callback_info_missing},
  {"lib/rulestead/credo/no_raw_traits_in_telemetry_meta.ex", :unknown_function},
  {"lib/rulestead/credo/no_socket_captured_in_async.ex", :callback_info_missing},
  {"lib/rulestead/credo/no_socket_captured_in_async.ex", :unknown_function},

  # Ecto Multi opaqueness and complex pattern match warnings
  {"lib/rulestead/store/ecto.ex", :call_without_opaque},
  {"lib/rulestead/webhooks/code_refs_plug.ex", :call_without_opaque},

  # Unfixable pattern match and type warnings
  {"lib/rulestead/fake.ex", :pattern_match},
  {"lib/rulestead/oban.ex", :pattern_match},
  {"lib/rulestead/oban/scheduled_execution_worker.ex", :pattern_match_cov},
  {"lib/rulestead/oban/webhook_delivery_worker.ex", :extra_range},
  {"lib/rulestead/promotion/apply.ex", :pattern_match_cov},
  {"lib/rulestead/runtime/backup/file_store.ex", :pattern_match_cov},
  {"lib/rulestead/runtime/cluster_case.ex", :missing_range},
  {"lib/rulestead/runtime/cluster_case.ex", :call},
  {"lib/rulestead/runtime/refresh.ex", :pattern_match_cov},
  {"lib/rulestead/telemetry.ex", :extra_range},

  # Post-GA band surfaces (v1.11) — tracking: dialyzer cleanup milestone
  {"lib/mix/tasks/rulestead.diff.ex", :extra_range},
  {"lib/mix/tasks/rulestead.diff.ex", :pattern_match},
  {"lib/mix/tasks/rulestead.diff.ex", :unused_fun},
  {"lib/mix/tasks/rulestead.import.ex", :extra_range},
  {"lib/mix/tasks/rulestead.validate.ex", :extra_range},
  {"lib/mix/tasks/rulestead.validate.ex", :pattern_match},
  {"lib/mix/tasks/rulestead.validate.ex", :unused_fun},
  {"lib/rulestead.ex", :extra_range},
  {"lib/rulestead/evaluator.ex", :pattern_match_cov},
  {"lib/rulestead/explainer.ex", :pattern_match_cov},
  {"lib/rulestead/fake.ex", :call},
  {"lib/rulestead/fake.ex", :guard_fail},
  {"lib/rulestead/fake.ex", :no_return},
  {"lib/rulestead/fake.ex", :pattern_match_cov},
  {"lib/rulestead/fake.ex", :unused_fun},
  {"lib/rulestead/fake/control.ex", :call},
  {"lib/rulestead/fake/control.ex", :no_return},
  {"lib/rulestead/governance/audience_mutation_change_request.ex", :guard_fail},
  {"lib/rulestead/governance/rollout_auto_advance.ex", :pattern_match_cov},
  {"lib/rulestead/manifest/diff.ex", :extra_range},
  {"lib/rulestead/manifest/diff.ex", :no_return},
  {"lib/rulestead/manifest/diff.ex", :unused_fun},
  {"lib/rulestead/manifest/import.ex", :call},
  {"lib/rulestead/manifest/import.ex", :extra_range},
  {"lib/rulestead/manifest/import.ex", :guard_fail},
  {"lib/rulestead/manifest/import.ex", :invalid_contract},
  {"lib/rulestead/manifest/import.ex", :no_return},
  {"lib/rulestead/manifest/import.ex", :pattern_match},
  {"lib/rulestead/manifest/import.ex", :unused_fun},
  {"lib/rulestead/manifest/validate.ex", :call},
  {"lib/rulestead/manifest/validate.ex", :extra_range},
  {"lib/rulestead/manifest/validate.ex", :no_return},
  {"lib/rulestead/manifest/validate.ex", :unused_fun},
  {"lib/rulestead/promotion/apply.ex", :call},
  {"lib/rulestead/promotion/apply.ex", :guard_fail},
  {"lib/rulestead/promotion/apply.ex", :invalid_contract},
  {"lib/rulestead/promotion/apply.ex", :no_return},
  {"lib/rulestead/promotion/compare.ex", :call},
  {"lib/rulestead/promotion/compare.ex", :invalid_contract},
  {"lib/rulestead/promotion/compare.ex", :no_return},
  {"lib/rulestead/promotion/compare.ex", :unused_fun},
  {"lib/rulestead/store/ecto.ex", :call},
  {"lib/rulestead/store/ecto.ex", :guard_fail},
  {"lib/rulestead/store/ecto.ex", :missing_range},
  {"lib/rulestead/store/ecto.ex", :no_return},
  {"lib/rulestead/store/ecto.ex", :pattern_match},
  {"lib/rulestead/store/ecto.ex", :pattern_match_cov},
  {"lib/rulestead/store/ecto.ex", :unused_fun}
]